import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar' | 'sv';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
});

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.products': 'Products',
    'nav.orders': 'Orders',
    'nav.events': 'Events',
    'nav.users': 'Users',
    'nav.settings': 'Settings',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Overview of your e-commerce performance',
    'dashboard.totalRevenue': 'Total Revenue',
    'dashboard.totalOrders': 'Total Orders',
    'dashboard.totalProducts': 'Total Products',
    'dashboard.activeUsers': 'Active Users',
    
    // Products
    'products.title': 'Products',
    'products.subtitle': 'Manage your product inventory and details',
    'products.addProduct': 'Add Product',
    'products.searchPlaceholder': 'Search products...',
    'products.noProducts': 'No products found',
    'products.image': 'Image',
    'products.product': 'Product',
    'products.category': 'Category',
    'products.price': 'Price',
    'products.stock': 'Stock',
    'products.status': 'Status',
    'products.actions': 'Actions',
    'products.edit': 'Edit',
    'products.delete': 'Delete',
    'products.deleteConfirmTitle': 'Delete Product',
    'products.deleteConfirmMessage': 'Are you sure you want to delete this product?',
    'products.deleting': 'Deleting...',
    'products.deleteSuccess': 'Product deleted successfully',
    'products.deleteError': 'Failed to delete product',
    'products.inStock': 'In Stock',
    'products.lowStock': 'Low Stock',
    'products.outOfStock': 'Out of Stock',
    'products.viewDetails': 'View complete product information',
    'products.images': 'Product Images',
    'products.units': 'units',
    'products.featured': 'Featured',
    'products.pricing': 'Pricing Information',
    'products.originalPrice': 'Original Price',
    'products.discountedPrice': 'Discounted Price',
    'products.currency': 'Currency',
    'products.description': 'Description',
    'products.noDescription': 'No description available',
    'products.tags': 'Tags',
    'products.createdAt': 'Created At',
    'products.updatedAt': 'Updated At',
    'products.productNotFound': 'Product not found',
    'products.slug': 'Slug',
    
    // Orders
    'orders.title': 'Orders',
    'orders.subtitle': 'Manage and track customer orders',
    'orders.orderId': 'Order ID',
    'orders.customer': 'Customer',
    'orders.status': 'Status',
    'orders.items': 'Items',
    'orders.total': 'Total',
    'orders.date': 'Date',
    'orders.actions': 'Actions',
    'orders.view': 'View',
    'orders.noOrders': 'No orders found',
    'orders.pending': 'Pending',
    'orders.processing': 'Processing',
    'orders.shipped': 'Shipped',
    'orders.delivered': 'Delivered',
    'orders.cancelled': 'Cancelled',
    'orders.last7DaysPerformance': 'Last 7 Days Performance',
    
    // Events
    'events.title': 'Events',
    'events.subtitle': 'Manage promotional events and banners',
    'events.addEvent': 'Add Event',
    'events.color': 'Color',
    'events.startDate': 'Start Date',
    'events.endDate': 'End Date',
    'events.status': 'Status',
    'events.active': 'Active',
    'events.inactive': 'Inactive',
    'events.expired': 'Expired',
    'events.edit': 'Edit',
    'events.duplicate': 'Duplicate',
    'events.delete': 'Delete',
    
    // Users
    'users.title': 'Admin Users',
    'users.subtitle': 'Manage admin users and their permissions',
    'users.addUser': 'Add User',
    'users.user': 'User',
    'users.role': 'Role',
    'users.lastSignIn': 'Last Sign In',
    'users.created': 'Created',
    'users.actions': 'Actions',
    'users.editRole': 'Edit Role',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Configure your dashboard preferences',
    'settings.appearance': 'Appearance',
    'settings.theme': 'Theme',
    'settings.themeDesc': 'Switch between light and dark mode',
    'settings.language': 'Language & Region',
    'settings.languageDesc': 'Set your preferred language and currency',
    'settings.dashboardLanguage': 'Dashboard Language',
    'settings.defaultCurrency': 'Default Currency',
    'settings.timezone': 'Timezone',
    'settings.savePreferences': 'Save Preferences',
    'settings.notifications': 'Notifications',
    'settings.notificationsDesc': 'Manage your notification preferences',
    'settings.inventory': 'Inventory Settings',
    'settings.inventoryDesc': 'Configure inventory management options',
    'settings.email': 'Email Settings',
    'settings.emailDesc': 'Configure email notifications for customers',
    'settings.analytics': 'Analytics & Reports',
    'settings.analyticsDesc': 'Configure reporting and analytics options',
    'settings.storeInfo': 'Store Information',
    'settings.storeInfoDesc': 'Update your store details',
    'settings.storeName': 'Store Name',
    'settings.contactEmail': 'Contact Email',
    'settings.updateStoreInfo': 'Update Store Info',
    'settings.lowStockAlerts': 'Low Stock Alerts',
    'settings.lowStockAlertsDesc': 'Get notified when products run low',
    'settings.newOrderNotifications': 'New Order Notifications',
    'settings.newOrderNotificationsDesc': 'Receive alerts for new orders',
    'settings.orderStatusUpdates': 'Order Status Updates',
    'settings.orderStatusUpdatesDesc': 'Notify when order status changes',
    'settings.productReviews': 'Product Reviews',
    'settings.productReviewsDesc': 'Get notified of new customer reviews',
    'settings.lowStockThreshold': 'Low Stock Threshold',
    'settings.lowStockThresholdDesc': 'Alert when stock falls below this number',
    'settings.autoHideOutOfStock': 'Auto-hide Out of Stock',
    'settings.autoHideOutOfStockDesc': 'Hide products with zero stock',
    'settings.trackInventory': 'Track Inventory',
    'settings.trackInventoryDesc': 'Enable stock tracking for products',
    'settings.orderConfirmation': 'Order Confirmation',
    'settings.orderConfirmationDesc': 'Send email when order is placed',
    'settings.shippingUpdates': 'Shipping Updates',
    'settings.shippingUpdatesDesc': 'Email customers about shipping status',
    'settings.deliveryConfirmation': 'Delivery Confirmation',
    'settings.deliveryConfirmationDesc': 'Notify when order is delivered',
    'settings.replyToEmail': 'Reply-To Email',
    'settings.dailySalesReport': 'Daily Sales Report',
    'settings.dailySalesReportDesc': 'Receive daily sales summary via email',
    'settings.weeklyPerformanceReport': 'Weekly Performance Report',
    'settings.weeklyPerformanceReportDesc': 'Get weekly analytics report',
    'settings.exportDataAccess': 'Export Data Access',
    'settings.exportDataAccess Desc': 'Allow exporting orders and products',
    'settings.reportDay': 'Report Day',
    
    // Dialogs & Forms
    'dialog.addUser': 'Add New Admin User',
    'dialog.addUserDesc': 'Create a new admin user with specific role and permissions',
    'dialog.email': 'Email',
    'dialog.password': 'Password',
    'dialog.passwordMin': 'Minimum 6 characters',
    'dialog.role': 'Role',
    'dialog.selectRole': 'Select role',
    'dialog.superAdmin': 'Super Admin - Full access',
    'dialog.admin': 'Admin - Manage products, orders, users',
    'dialog.editor': 'Editor - Manage products and orders',
    'dialog.viewer': 'Viewer - Read-only access',
    'dialog.createUser': 'Create User',
    'dialog.creating': 'Creating...',
    'dialog.addEvent': 'Add Event',
    'dialog.editEvent': 'Edit Event',
    'dialog.eventDetails': 'Configure event details and appearance',
    'dialog.titleEnglish': 'Title (English)',
    'dialog.titleArabic': 'Title (Arabic)',
    'dialog.titleSwedish': 'Title (Swedish)',
    'dialog.descriptionEnglish': 'Description (English)',
    'dialog.descriptionArabic': 'Description (Arabic)',
    'dialog.descriptionSwedish': 'Description (Swedish)',
    'dialog.link': 'Link',
    'dialog.backgroundColor': 'Background Color',
    'dialog.textColor': 'Text Color',
    'dialog.startDate': 'Start Date',
    'dialog.endDate': 'End Date',
    'dialog.discountPercentage': 'Discount Percentage',
    'dialog.active': 'Active',
    'dialog.saveEvent': 'Save Event',
    'dialog.saving': 'Saving...',
    'dialog.addProduct': 'Add Product',
    'dialog.editProduct': 'Edit Product',
    'dialog.productDetails': 'Enter product information',
    'dialog.images': 'Images',
    'dialog.uploadImages': 'Upload Images',
    'dialog.uploading': 'Uploading...',
    'dialog.autoTranslate': 'Auto-Translate',
    'dialog.sourceLanguage': 'Source Language',
    'dialog.translate': 'Translate',
    'dialog.translating': 'Translating...',
    'dialog.slug': 'Slug',
    'dialog.category': 'Category',
    'dialog.selectCategory': 'Select category',
    'dialog.price': 'Price',
    'dialog.currency': 'Currency',
    'dialog.stock': 'Stock',
    'dialog.featured': 'Featured',
    'dialog.saveProduct': 'Save Product',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.loading': 'Loading...',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.actions': 'Actions',
  },
  ar: {
    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.products': 'المنتجات',
    'nav.orders': 'الطلبات',
    'nav.events': 'الفعاليات',
    'nav.users': 'المستخدمين',
    'nav.settings': 'الإعدادات',
    
    // Dashboard
    'dashboard.title': 'لوحة التحكم',
    'dashboard.subtitle': 'نظرة عامة على أداء متجرك الإلكتروني',
    'dashboard.totalRevenue': 'إجمالي الإيرادات',
    'dashboard.totalOrders': 'إجمالي الطلبات',
    'dashboard.totalProducts': 'إجمالي المنتجات',
    'dashboard.activeUsers': 'المستخدمون النشطون',
    
    // Products
    'products.title': 'المنتجات',
    'products.subtitle': 'إدارة مخزون المنتجات والتفاصيل',
    'products.addProduct': 'إضافة منتج',
    'products.searchPlaceholder': 'البحث عن المنتجات...',
    'products.noProducts': 'لا توجد منتجات',
    'products.image': 'الصورة',
    'products.product': 'المنتج',
    'products.category': 'الفئة',
    'products.price': 'السعر',
    'products.stock': 'المخزون',
    'products.status': 'الحالة',
    'products.actions': 'الإجراءات',
    'products.edit': 'تعديل',
    'products.delete': 'حذف',
    'products.deleteConfirmTitle': 'حذف المنتج',
    'products.deleteConfirmMessage': 'هل أنت متأكد أنك تريد حذف هذا المنتج؟ لا تحذفه فوراً.',
    'products.deleting': 'جاري الحذف...',
    'products.deleteSuccess': 'تم حذف المنتج بنجاح',
    'products.deleteError': 'فشل حذف المنتج',
    'products.inStock': 'متوفر',
    'products.lowStock': 'مخزون منخفض',
    'products.outOfStock': 'غير متوفر',
    'products.viewDetails': 'عرض معلومات المنتج الكاملة',
    'products.images': 'صور المنتج',
    'products.units': 'وحدة',
    'products.featured': 'مميز',
    'products.pricing': 'معلومات التسعير',
    'products.originalPrice': 'السعر الأصلي',
    'products.discountedPrice': 'السعر المخفض',
    'products.currency': 'العملة',
    'products.description': 'الوصف',
    'products.noDescription': 'لا يوجد وصف متاح',
    'products.tags': 'العلامات',
    'products.createdAt': 'تاريخ الإنشاء',
    'products.updatedAt': 'تاريخ التحديث',
    'products.productNotFound': 'المنتج غير موجود',
    'products.slug': 'المعرف',
    
    // Orders
    'orders.title': 'الطلبات',
    'orders.subtitle': 'إدارة وتتبع طلبات العملاء',
    'orders.orderId': 'رقم الطلب',
    'orders.customer': 'العميل',
    'orders.status': 'الحالة',
    'orders.items': 'العناصر',
    'orders.total': 'المجموع',
    'orders.date': 'التاريخ',
    'orders.actions': 'الإجراءات',
    'orders.view': 'عرض',
    'orders.noOrders': 'لا توجد طلبات',
    'orders.pending': 'قيد الانتظار',
    'orders.processing': 'قيد المعالجة',
    'orders.shipped': 'تم الشحن',
    'orders.delivered': 'تم التسليم',
    'orders.cancelled': 'ملغي',
    'orders.last7DaysPerformance': 'أداء آخر 7 أيام',
    
    // Events
    'events.title': 'الفعاليات',
    'events.subtitle': 'إدارة الفعاليات الترويجية واللافتات',
    'events.addEvent': 'إضافة فعالية',
    'events.color': 'اللون',
    'events.startDate': 'تاريخ البداية',
    'events.endDate': 'تاريخ النهاية',
    'events.status': 'الحالة',
    'events.active': 'نشط',
    'events.inactive': 'غير نشط',
    'events.expired': 'منتهي',
    'events.edit': 'تعديل',
    'events.duplicate': 'نسخ',
    'events.delete': 'حذف',
    
    // Users
    'users.title': 'مستخدمو الإدارة',
    'users.subtitle': 'إدارة المستخدمين الإداريين وصلاحياتهم',
    'users.addUser': 'إضافة مستخدم',
    'users.user': 'المستخدم',
    'users.role': 'الدور',
    'users.lastSignIn': 'آخر تسجيل دخول',
    'users.created': 'تاريخ الإنشاء',
    'users.actions': 'الإجراءات',
    'users.editRole': 'تعديل الدور',
    
    // Settings
    'settings.title': 'الإعدادات',
    'settings.subtitle': 'تكوين تفضيلات لوحة التحكم',
    'settings.appearance': 'المظهر',
    'settings.theme': 'السمة',
    'settings.themeDesc': 'التبديل بين الوضع الفاتح والداكن',
    'settings.language': 'اللغة والمنطقة',
    'settings.languageDesc': 'تعيين اللغة والعملة المفضلة',
    'settings.dashboardLanguage': 'لغة لوحة التحكم',
    'settings.defaultCurrency': 'العملة الافتراضية',
    'settings.timezone': 'المنطقة الزمنية',
    'settings.savePreferences': 'حفظ التفضيلات',
    'settings.notifications': 'الإشعارات',
    'settings.notificationsDesc': 'إدارة تفضيلات الإشعارات',
    'settings.inventory': 'إعدادات المخزون',
    'settings.inventoryDesc': 'تكوين خيارات إدارة المخزون',
    'settings.email': 'إعدادات البريد الإلكتروني',
    'settings.emailDesc': 'تكوين إشعارات البريد الإلكتروني للعملاء',
    'settings.analytics': 'التحليلات والتقارير',
    'settings.analyticsDesc': 'تكوين خيارات التقارير والتحليلات',
    'settings.storeInfo': 'معلومات المتجر',
    'settings.storeInfoDesc': 'تحديث تفاصيل متجرك',
    'settings.storeName': 'اسم المتجر',
    'settings.contactEmail': 'البريد الإلكتروني للتواصل',
    'settings.updateStoreInfo': 'تحديث معلومات المتجر',
    'settings.lowStockAlerts': 'تنبيهات المخزون المنخفض',
    'settings.lowStockAlertsDesc': 'احصل على إشعار عندما ينخفض المخزون',
    'settings.newOrderNotifications': 'إشعارات الطلبات الجديدة',
    'settings.newOrderNotificationsDesc': 'تلقي تنبيهات للطلبات الجديدة',
    'settings.orderStatusUpdates': 'تحديثات حالة الطلب',
    'settings.orderStatusUpdatesDesc': 'إشعار عند تغيير حالة الطلب',
    'settings.productReviews': 'مراجعات المنتجات',
    'settings.productReviewsDesc': 'احصل على إشعار بمراجعات العملاء الجديدة',
    'settings.lowStockThreshold': 'حد المخزون المنخفض',
    'settings.lowStockThresholdDesc': 'تنبيه عندما ينخفض المخزون عن هذا الرقم',
    'settings.autoHideOutOfStock': 'إخفاء تلقائي للمنتجات غير المتوفرة',
    'settings.autoHideOutOfStockDesc': 'إخفاء المنتجات ذات المخزون الصفري',
    'settings.trackInventory': 'تتبع المخزون',
    'settings.trackInventoryDesc': 'تفعيل تتبع المخزون للمنتجات',
    'settings.orderConfirmation': 'تأكيد الطلب',
    'settings.orderConfirmationDesc': 'إرسال بريد إلكتروني عند تقديم الطلب',
    'settings.shippingUpdates': 'تحديثات الشحن',
    'settings.shippingUpdatesDesc': 'إرسال بريد إلكتروني للعملاء حول حالة الشحن',
    'settings.deliveryConfirmation': 'تأكيد التسليم',
    'settings.deliveryConfirmationDesc': 'إشعار عند تسليم الطلب',
    'settings.replyToEmail': 'البريد الإلكتروني للرد',
    'settings.dailySalesReport': 'تقرير المبيعات اليومي',
    'settings.dailySalesReportDesc': 'تلقي ملخص المبيعات اليومي عبر البريد الإلكتروني',
    'settings.weeklyPerformanceReport': 'تقرير الأداء الأسبوعي',
    'settings.weeklyPerformanceReportDesc': 'الحصول على تقرير التحليلات الأسبوعي',
    'settings.exportDataAccess': 'الوصول إلى تصدير البيانات',
    'settings.exportDataAccessDesc': 'السماح بتصدير الطلبات والمنتجات',
    'settings.reportDay': 'يوم التقرير',
    
    // Dialogs & Forms
    'dialog.addUser': 'إضافة مستخدم إداري جديد',
    'dialog.addUserDesc': 'إنشاء مستخدم إداري جديد بدور وصلاحيات محددة',
    'dialog.email': 'البريد الإلكتروني',
    'dialog.password': 'كلمة المرور',
    'dialog.passwordMin': 'الحد الأدنى 6 أحرف',
    'dialog.role': 'الدور',
    'dialog.selectRole': 'اختر الدور',
    'dialog.superAdmin': 'مدير عام - وصول كامل',
    'dialog.admin': 'مدير - إدارة المنتجات والطلبات والمستخدمين',
    'dialog.editor': 'محرر - إدارة المنتجات والطلبات',
    'dialog.viewer': 'مشاهد - وصول للقراءة فقط',
    'dialog.createUser': 'إنشاء مستخدم',
    'dialog.creating': 'جاري الإنشاء...',
    'dialog.addEvent': 'إضافة فعالية',
    'dialog.editEvent': 'تعديل الفعالية',
    'dialog.eventDetails': 'تكوين تفاصيل الفعالية والمظهر',
    'dialog.titleEnglish': 'العنوان (الإنجليزية)',
    'dialog.titleArabic': 'العنوان (العربية)',
    'dialog.titleSwedish': 'العنوان (السويدية)',
    'dialog.descriptionEnglish': 'الوصف (الإنجليزية)',
    'dialog.descriptionArabic': 'الوصف (العربية)',
    'dialog.descriptionSwedish': 'الوصف (السويدية)',
    'dialog.link': 'الرابط',
    'dialog.backgroundColor': 'لون الخلفية',
    'dialog.textColor': 'لون النص',
    'dialog.startDate': 'تاريخ البداية',
    'dialog.endDate': 'تاريخ النهاية',
    'dialog.discountPercentage': 'نسبة الخصم',
    'dialog.active': 'نشط',
    'dialog.saveEvent': 'حفظ الفعالية',
    'dialog.saving': 'جاري الحفظ...',
    'dialog.addProduct': 'إضافة منتج',
    'dialog.editProduct': 'تعديل المنتج',
    'dialog.productDetails': 'أدخل معلومات المنتج',
    'dialog.images': 'الصور',
    'dialog.uploadImages': 'رفع الصور',
    'dialog.uploading': 'جاري الرفع...',
    'dialog.autoTranslate': 'ترجمة تلقائية',
    'dialog.sourceLanguage': 'اللغة المصدر',
    'dialog.translate': 'ترجمة',
    'dialog.translating': 'جاري الترجمة...',
    'dialog.slug': 'المعرف',
    'dialog.category': 'الفئة',
    'dialog.selectCategory': 'اختر الفئة',
    'dialog.price': 'السعر',
    'dialog.currency': 'العملة',
    'dialog.stock': 'المخزون',
    'dialog.featured': 'مميز',
    'dialog.saveProduct': 'حفظ المنتج',
    
    // Common
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.add': 'إضافة',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.loading': 'جاري التحميل...',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.confirm': 'تأكيد',
    'common.close': 'إغلاق',
    'common.actions': 'الإجراءات',
  },
  sv: {
    // Navigation
    'nav.dashboard': 'Instrumentpanel',
    'nav.products': 'Produkter',
    'nav.orders': 'Beställningar',
    'nav.events': 'Evenemang',
    'nav.users': 'Användare',
    'nav.settings': 'Inställningar',
    
    // Dashboard
    'dashboard.title': 'Instrumentpanel',
    'dashboard.subtitle': 'Översikt över din e-handelsprestanda',
    'dashboard.totalRevenue': 'Total intäkt',
    'dashboard.totalOrders': 'Totalt antal beställningar',
    'dashboard.totalProducts': 'Totalt antal produkter',
    'dashboard.activeUsers': 'Aktiva användare',
    
    // Products
    'products.title': 'Produkter',
    'products.subtitle': 'Hantera ditt produktlager och detaljer',
    'products.addProduct': 'Lägg till produkt',
    'products.searchPlaceholder': 'Sök produkter...',
    'products.noProducts': 'Inga produkter hittades',
    'products.image': 'Bild',
    'products.product': 'Produkt',
    'products.category': 'Kategori',
    'products.price': 'Pris',
    'products.stock': 'Lager',
    'products.status': 'Status',
    'products.actions': 'Åtgärder',
    'products.edit': 'Redigera',
    'products.delete': 'Ta bort',
    'products.deleteConfirmTitle': 'Ta bort produkt',
    'products.deleteConfirmMessage': 'Är du säker på att du vill ta bort denna produkt? Ta inte bort den omedelbart.',
    'products.deleting': 'Tar bort...',
    'products.deleteSuccess': 'Produkten har tagits bort',
    'products.deleteError': 'Misslyckades med att ta bort produkt',
    'products.inStock': 'I lager',
    'products.lowStock': 'Lågt lager',
    'products.outOfStock': 'Slut i lager',
    'products.viewDetails': 'Visa komplett produktinformation',
    'products.images': 'Produktbilder',
    'products.units': 'enheter',
    'products.featured': 'Utvald',
    'products.pricing': 'Prisinformation',
    'products.originalPrice': 'Ursprungligt pris',
    'products.discountedPrice': 'Rabatterat pris',
    'products.currency': 'Valuta',
    'products.description': 'Beskrivning',
    'products.noDescription': 'Ingen beskrivning tillgänglig',
    'products.tags': 'Taggar',
    'products.createdAt': 'Skapad',
    'products.updatedAt': 'Uppdaterad',
    'products.productNotFound': 'Produkt hittades inte',
    'products.slug': 'Slug',
    
    // Orders
    'orders.title': 'Beställningar',
    'orders.subtitle': 'Hantera och spåra kundbeställningar',
    'orders.orderId': 'Beställnings-ID',
    'orders.customer': 'Kund',
    'orders.status': 'Status',
    'orders.items': 'Artiklar',
    'orders.total': 'Totalt',
    'orders.date': 'Datum',
    'orders.actions': 'Åtgärder',
    'orders.view': 'Visa',
    'orders.noOrders': 'Inga beställningar hittades',
    'orders.pending': 'Väntande',
    'orders.processing': 'Bearbetas',
    'orders.shipped': 'Skickad',
    'orders.delivered': 'Levererad',
    'orders.cancelled': 'Avbruten',
    'orders.last7DaysPerformance': 'Senaste 7 dagarnas prestanda',
    
    // Events
    'events.title': 'Evenemang',
    'events.subtitle': 'Hantera kampanjevenemang och banners',
    'events.addEvent': 'Lägg till evenemang',
    'events.color': 'Färg',
    'events.startDate': 'Startdatum',
    'events.endDate': 'Slutdatum',
    'events.status': 'Status',
    'events.active': 'Aktiv',
    'events.inactive': 'Inaktiv',
    'events.expired': 'Utgången',
    'events.edit': 'Redigera',
    'events.duplicate': 'Duplicera',
    'events.delete': 'Ta bort',
    
    // Users
    'users.title': 'Administratörer',
    'users.subtitle': 'Hantera administratörer och deras behörigheter',
    'users.addUser': 'Lägg till användare',
    'users.user': 'Användare',
    'users.role': 'Roll',
    'users.lastSignIn': 'Senaste inloggning',
    'users.created': 'Skapad',
    'users.actions': 'Åtgärder',
    'users.editRole': 'Redigera roll',
    
    // Settings
    'settings.title': 'Inställningar',
    'settings.subtitle': 'Konfigurera dina instrumentpanelsinställningar',
    'settings.appearance': 'Utseende',
    'settings.theme': 'Tema',
    'settings.themeDesc': 'Växla mellan ljust och mörkt läge',
    'settings.language': 'Språk och region',
    'settings.languageDesc': 'Ställ in ditt föredragna språk och valuta',
    'settings.dashboardLanguage': 'Instrumentpanelens språk',
    'settings.defaultCurrency': 'Standardvaluta',
    'settings.timezone': 'Tidszon',
    'settings.savePreferences': 'Spara inställningar',
    'settings.notifications': 'Aviseringar',
    'settings.notificationsDesc': 'Hantera dina aviseringsinställningar',
    'settings.inventory': 'Lagerinställningar',
    'settings.inventoryDesc': 'Konfigurera alternativ för lagerhantering',
    'settings.email': 'E-postinställningar',
    'settings.emailDesc': 'Konfigurera e-postaviseringar för kunder',
    'settings.analytics': 'Analys och rapporter',
    'settings.analyticsDesc': 'Konfigurera rapportering och analysinställningar',
    'settings.storeInfo': 'Butiksinformation',
    'settings.storeInfoDesc': 'Uppdatera dina butiksdetaljer',
    'settings.storeName': 'Butiksnamn',
    'settings.contactEmail': 'Kontakt-e-post',
    'settings.updateStoreInfo': 'Uppdatera butiksinformation',
    'settings.lowStockAlerts': 'Låglagerlarm',
    'settings.lowStockAlertsDesc': 'Få meddelande när produkter tar slut',
    'settings.newOrderNotifications': 'Nya beställningsaviseringar',
    'settings.newOrderNotificationsDesc': 'Ta emot aviseringar för nya beställningar',
    'settings.orderStatusUpdates': 'Beställningsstatusuppdateringar',
    'settings.orderStatusUpdatesDesc': 'Meddela när beställningsstatus ändras',
    'settings.productReviews': 'Produktrecensioner',
    'settings.productReviewsDesc': 'Få meddelande om nya kundrecensioner',
    'settings.lowStockThreshold': 'Låglagergräns',
    'settings.lowStockThresholdDesc': 'Varna när lagret faller under detta nummer',
    'settings.autoHideOutOfStock': 'Dölj automatiskt slut i lager',
    'settings.autoHideOutOfStockDesc': 'Dölj produkter med noll lager',
    'settings.trackInventory': 'Spåra lager',
    'settings.trackInventoryDesc': 'Aktivera lagerspårning för produkter',
    'settings.orderConfirmation': 'Orderbekräftelse',
    'settings.orderConfirmationDesc': 'Skicka e-post när beställning läggs',
    'settings.shippingUpdates': 'Fraktuppdateringar',
    'settings.shippingUpdatesDesc': 'E-posta kunder om fraktstatus',
    'settings.deliveryConfirmation': 'Leveransbekräftelse',
    'settings.deliveryConfirmationDesc': 'Meddela när beställning levereras',
    'settings.replyToEmail': 'Svara-till e-post',
    'settings.dailySalesReport': 'Daglig försäljningsrapport',
    'settings.dailySalesReportDesc': 'Ta emot daglig försäljningssammanfattning via e-post',
    'settings.weeklyPerformanceReport': 'Veckovis prestationsrapport',
    'settings.weeklyPerformanceReportDesc': 'Få veckovis analysrapport',
    'settings.exportDataAccess': 'Exportera dataåtkomst',
    'settings.exportDataAccessDesc': 'Tillåt export av beställningar och produkter',
    'settings.reportDay': 'Rapportdag',
    
    // Dialogs & Forms
    'dialog.addUser': 'Lägg till ny administratör',
    'dialog.addUserDesc': 'Skapa en ny administratör med specifik roll och behörigheter',
    'dialog.email': 'E-post',
    'dialog.password': 'Lösenord',
    'dialog.passwordMin': 'Minst 6 tecken',
    'dialog.role': 'Roll',
    'dialog.selectRole': 'Välj roll',
    'dialog.superAdmin': 'Superadministratör - Full åtkomst',
    'dialog.admin': 'Administratör - Hantera produkter, beställningar, användare',
    'dialog.editor': 'Redaktör - Hantera produkter och beställningar',
    'dialog.viewer': 'Visare - Endast läsåtkomst',
    'dialog.createUser': 'Skapa användare',
    'dialog.creating': 'Skapar...',
    'dialog.addEvent': 'Lägg till evenemang',
    'dialog.editEvent': 'Redigera evenemang',
    'dialog.eventDetails': 'Konfigurera evenemangsdetaljer och utseende',
    'dialog.titleEnglish': 'Titel (Engelska)',
    'dialog.titleArabic': 'Titel (Arabiska)',
    'dialog.titleSwedish': 'Titel (Svenska)',
    'dialog.descriptionEnglish': 'Beskrivning (Engelska)',
    'dialog.descriptionArabic': 'Beskrivning (Arabiska)',
    'dialog.descriptionSwedish': 'Beskrivning (Svenska)',
    'dialog.link': 'Länk',
    'dialog.backgroundColor': 'Bakgrundsfärg',
    'dialog.textColor': 'Textfärg',
    'dialog.startDate': 'Startdatum',
    'dialog.endDate': 'Slutdatum',
    'dialog.discountPercentage': 'Rabatt procent',
    'dialog.active': 'Aktiv',
    'dialog.saveEvent': 'Spara evenemang',
    'dialog.saving': 'Sparar...',
    'dialog.addProduct': 'Lägg till produkt',
    'dialog.editProduct': 'Redigera produkt',
    'dialog.productDetails': 'Ange produktinformation',
    'dialog.images': 'Bilder',
    'dialog.uploadImages': 'Ladda upp bilder',
    'dialog.uploading': 'Laddar upp...',
    'dialog.autoTranslate': 'Auto-översätt',
    'dialog.sourceLanguage': 'Källspråk',
    'dialog.translate': 'Översätt',
    'dialog.translating': 'Översätter...',
    'dialog.slug': 'Slug',
    'dialog.category': 'Kategori',
    'dialog.selectCategory': 'Välj kategori',
    'dialog.price': 'Pris',
    'dialog.currency': 'Valuta',
    'dialog.stock': 'Lager',
    'dialog.featured': 'Utvald',
    'dialog.saveProduct': 'Spara produkt',
    
    // Common
    'common.save': 'Spara',
    'common.cancel': 'Avbryt',
    'common.delete': 'Ta bort',
    'common.edit': 'Redigera',
    'common.add': 'Lägg till',
    'common.search': 'Sök',
    'common.filter': 'Filtrera',
    'common.loading': 'Laddar...',
    'common.yes': 'Ja',
    'common.no': 'Nej',
    'common.confirm': 'Bekräfta',
    'common.close': 'Stäng',
    'common.actions': 'Åtgärder',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('dashboard-language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('dashboard-language', language);
    // Set document direction for RTL languages
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

